# Generated by Django 3.2.25 on 2024-05-21 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_team_member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(default='Hyderabad')),
                ('contact', models.IntegerField(default='123456789')),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('categories', models.CharField(max_length=20)),
                ('designations', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
