# Generated by Django 3.2.25 on 2024-05-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_create_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_project',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', to='pms.create_team_member'),
        ),
    ]
